# Generated by Django 5.0.6 on 2024-06-06 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('f027ba5d-21eb-4250-a64c-29ce4ff525d8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('f027ba5d-21eb-4250-a64c-29ce4ff525d8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
