# Generated by Django 5.0.6 on 2024-06-06 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_codeverify_uu_id_alter_followers_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('e17c709c-b3e6-4a5b-bd87-590a22e92a38'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('e17c709c-b3e6-4a5b-bd87-590a22e92a38'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
