# Generated by Django 5.0.6 on 2024-06-11 23:19

import django.core.validators
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_codeverify_code_alter_codeverify_uu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('3adc9c0f-9233-44b7-a956-2641903be498'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpeg', '.png', '.jpg']), users.models.FileSizeValidator]),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('3adc9c0f-9233-44b7-a956-2641903be498'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
