# Generated by Django 5.0.6 on 2024-06-11 23:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_codeverify_uu_id_alter_followers_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('19da6c94-3606-4e32-b344-d171e8d4ebaa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('19da6c94-3606-4e32-b344-d171e8d4ebaa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
