# Generated by Django 5.0.6 on 2024-06-25 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_codeverify_uu_id_alter_followers_uu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='user_type',
            new_name='auth_type',
        ),
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('b15d03e6-de8e-484c-bf2b-32c733949705'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('b15d03e6-de8e-484c-bf2b-32c733949705'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
