# Generated by Django 5.0.6 on 2024-06-25 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_user_type_followers_auth_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('04d07db8-0c8e-4b73-ab37-f4217636df72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('04d07db8-0c8e-4b73-ab37-f4217636df72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
