# Generated by Django 5.0.6 on 2024-06-25 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_codeverify_uu_id_alter_followers_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('e1f65932-31fe-4b59-ad55-4e351581926a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('e1f65932-31fe-4b59-ad55-4e351581926a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
