# Generated by Django 5.0.6 on 2024-06-25 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_codeverify_uu_id_alter_followers_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('feb5c179-b8b9-4016-b8ac-e2f3d6982474'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('feb5c179-b8b9-4016-b8ac-e2f3d6982474'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
