# Generated by Django 5.0.6 on 2024-06-26 05:10

import django.core.validators
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_codeverify_uu_id_alter_followers_uu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('979af664-fb77-45c8-b104-89c95bdf3d72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpeg', '.png', '.jpg']), users.models.FileSizeValidator]),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('979af664-fb77-45c8-b104-89c95bdf3d72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
