# Generated by Django 5.0.6 on 2024-06-26 05:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_codeverify_uu_id_alter_followers_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('c7773919-584d-4e18-8eea-89773392d293'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('c7773919-584d-4e18-8eea-89773392d293'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
