# Generated by Django 5.0.6 on 2024-06-26 06:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_phone_followers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='codeverify',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('8b614b67-88e2-4623-ba81-35825a6d7f76'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='followers',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('8b614b67-88e2-4623-ba81-35825a6d7f76'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
