# Generated by Django 5.0.6 on 2024-06-26 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_codeverify_expire_time_alter_codeverify_uu_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeverify',
            name='uu_id',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='uu_id',
        ),
        migrations.AddField(
            model_name='codeverify',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05b08de8-66d2-4ed0-8800-7b6639e26821'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='followers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05b08de8-66d2-4ed0-8800-7b6639e26821'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
