# Generated by Django 5.0.6 on 2024-06-25 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('feb5c179-b8b9-4016-b8ac-e2f3d6982474'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commentslike',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('feb5c179-b8b9-4016-b8ac-e2f3d6982474'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('feb5c179-b8b9-4016-b8ac-e2f3d6982474'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('feb5c179-b8b9-4016-b8ac-e2f3d6982474'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
