# Generated by Django 5.0.6 on 2024-06-26 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_comments_uu_id_alter_commentslike_uu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('979af664-fb77-45c8-b104-89c95bdf3d72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commentslike',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('979af664-fb77-45c8-b104-89c95bdf3d72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('979af664-fb77-45c8-b104-89c95bdf3d72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('979af664-fb77-45c8-b104-89c95bdf3d72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
