# Generated by Django 5.0.6 on 2024-06-26 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_comments_uu_id_alter_commentslike_uu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('b670ea78-7ce8-48e2-b056-9fdd4930e56e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commentslike',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('b670ea78-7ce8-48e2-b056-9fdd4930e56e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('b670ea78-7ce8-48e2-b056-9fdd4930e56e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='uu_id',
            field=models.UUIDField(default=uuid.UUID('b670ea78-7ce8-48e2-b056-9fdd4930e56e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
