# Generated by Django 5.0.6 on 2024-06-26 06:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_alter_comments_uu_id_alter_commentslike_uu_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='uu_id',
        ),
        migrations.RemoveField(
            model_name='commentslike',
            name='uu_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uu_id',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='uu_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39be6b29-707e-4771-9923-7cbe779bed5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='commentslike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39be6b29-707e-4771-9923-7cbe779bed5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39be6b29-707e-4771-9923-7cbe779bed5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39be6b29-707e-4771-9923-7cbe779bed5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
